"""
Mock backend for local development of the JRM Media Advisor Streamlit app.

Returns deterministic, realistic-looking responses so the UI can be built
and iterated on without a live Databricks connection.

Activated by setting USE_MOCK_BACKEND=true in the environment.
"""

from __future__ import annotations

from jrm_advisor.app.backend import AppResponse

_MOCK_RESPONSES: dict[str, AppResponse] = {
    # ── KB-only ──────────────────────────────────────────────────────────────
    "what is sales uplift": AppResponse(
        text=(
            "Sales uplift measures the incremental sales generated by a campaign "
            "above the expected baseline. It is calculated as actual sales minus "
            "the modelled baseline, expressed either as an absolute value (€) or "
            "as a percentage of baseline sales.\n\n"
            "**How it is measured:** A statistical model estimates what sales "
            "would have been without the campaign (the baseline). Uplift is then "
            "the observed excess above that baseline during the campaign period.\n\n"
            "**Known limitation:** The baseline model assumes sales drivers remain "
            "stable; unusual external events (e.g. competitor promotions, supply "
            "disruptions) may distort the estimate."
        ),
    ),
    "what is ots": AppResponse(
        text=(
            "OTS (On-Shelf Time) measures the proportion of time a product is "
            "physically visible and available for purchase at the point of sale. "
            "It is a key in-store media quality metric: a campaign cannot drive "
            "sales if the promoted product is out of stock or obscured.\n\n"
            "**How it is measured:** OTS is tracked via store audit data or "
            "sensor-based shelf monitoring. A score of 100 % means the product "
            "was on-shelf throughout the measurement period.\n\n"
            "**Known limitation:** Store-level OTS correlation with sales uplift "
            "is not yet available in this tool."
        ),
    ),
    # ── Data-only ────────────────────────────────────────────────────────────
    "show weekly sales for heineken": AppResponse(
        text=(
            "Here are the weekly actual sales figures for the Heineken Pilsner W4 "
            "2024 campaign during the active campaign period."
        ),
        resolved_campaign_name="Heineken Pilsner W4 2024",
        genie_rows=[
            {"year_week": "202401", "actual_sales": "48320"},
            {"year_week": "202402", "actual_sales": "51740"},
            {"year_week": "202403", "actual_sales": "55180"},
            {"year_week": "202404", "actual_sales": "49900"},
        ],
        genie_sql=(
            "SELECT year_week, actual_sales "
            "FROM retail_media.campaign_results "
            "WHERE campaign_name = 'Heineken Pilsner W4 2024' "
            "ORDER BY year_week"
        ),
        visualization={
            "should_visualize": True,
            "chart_type": "line",
            "x_field": "year_week",
            "y_field": "actual_sales",
            "y_format": "currency",
            "decimals": 0,
            "scale": "identity",
            "style_preset": "jumbo",
        },
    ),
    "show uplift for coca-cola": AppResponse(
        text=(
            "The weekly sales uplift for the Coca-Cola Summer 2024 campaign "
            "is shown below. The campaign delivered positive uplift in three of "
            "four measured weeks, with week 202503 showing the strongest result."
        ),
        resolved_campaign_name="Coca-Cola Summer 2024",
        genie_rows=[
            {"year_week": "202501", "sales_uplift_percentage": "0.082"},
            {"year_week": "202502", "sales_uplift_percentage": "0.114"},
            {"year_week": "202503", "sales_uplift_percentage": "0.173"},
            {"year_week": "202504", "sales_uplift_percentage": "-0.021"},
        ],
        genie_sql=(
            "SELECT year_week, sales_uplift_percentage "
            "FROM retail_media.campaign_results "
            "WHERE campaign_name = 'Coca-Cola Summer 2024' "
            "ORDER BY year_week"
        ),
        visualization={
            "should_visualize": True,
            "chart_type": "bar",
            "x_field": "year_week",
            "y_field": "sales_uplift_percentage",
            "y_format": "percentage",
            "decimals": 1,
            "scale": "x100",
            "style_preset": "jumbo",
        },
    ),
    # ── Clarification ────────────────────────────────────────────────────────
    "show results for heineken": AppResponse(
        text=(
            "I found multiple campaigns that could match your question. "
            "Which campaign did you mean?\n\n"
            "- Heineken Pilsner W4 2024\n"
            "- Heineken 0.0 W4 2024\n\n"
            "Please reply with the full campaign name to continue."
        ),
        needs_clarification=True,
    ),
    # ── Out-of-scope ─────────────────────────────────────────────────────────
    "ropo analysis": AppResponse(
        text=(
            "ROPO analysis is not yet stakeholder-aligned and is not currently "
            "supported by the JRM Media Advisor."
        ),
    ),
    "store-level roi": AppResponse(
        text=(
            "Store-level ROI analysis is not yet supported in the JRM Media Advisor."
        ),
    ),
}

_DEFAULT_RESPONSE = AppResponse(
    text=(
        "I don't have a mock response for that question. "
        "In the live environment this would be routed to the appropriate "
        "sub-component (Knowledge Base or Genie). "
        "Try one of: 'what is sales uplift', 'show weekly sales for heineken', "
        "'show results for heineken', or 'ropo analysis'."
    ),
)


class MockBackend:
    """Deterministic mock backend for local UI development."""

    def ask(self, question: str) -> AppResponse:
        key = question.lower().strip().rstrip("?")
        # Exact match first
        if key in _MOCK_RESPONSES:
            return _MOCK_RESPONSES[key]
        # Substring match — pick first key that appears in the question
        for mock_key, response in _MOCK_RESPONSES.items():
            if mock_key in key:
                return response
        return _DEFAULT_RESPONSE
